/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 20:02:43 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.dividir((-746), (-395));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.soma(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.soma((-3358), 510);
      assertEquals((-2848), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.dividir(0, 46);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.dividir((-2848), 1);
      assertEquals((-2848), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.dividir((-412), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Divis\u00C3\u00A3o por zero
         //
         verifyException("Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      int int0 = calculadora0.soma(2059, (-32));
      assertEquals(2027, int0);
  }
}
